# Generated by Django 5.2.7 on 2025-10-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название работы'),
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Услуга товара',
                'verbose_name_plural': 'Услуги товаров',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Размер стелы')),
                ('stela_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стела')),
                ('portrait_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Портрет')),
                ('text_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ФИО + даты')),
                ('installation_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Установка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.productservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
                'ordering': ['size'],
            },
        ),
    ]
