# Generated by Django 5.2.7 on 2025-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_workphoto_title_productservice_serviceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='installation_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Установка'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='portrait_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Портрет'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Размер/Название'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='stela_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стела'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='text_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ФИО + даты'),
        ),
    ]
