# Generated by Django 5.2.7 on 2025-10-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='service',
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название размера/услуги')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товара',
                'ordering': ['price'],
            },
        ),
        migrations.DeleteModel(
            name='ProductService',
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
    ]
