# Generated by Django 5.2.7 on 2025-10-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_serviceprice_service_productprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название работы'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "120x200 см"', max_length=200, verbose_name='Название опции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена опции')),
                ('description', models.TextField(blank=True, verbose_name='Описание опции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Опция товара',
                'verbose_name_plural': 'Опции товара',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/options/', verbose_name='Фото опции')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productoption', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Фото опции',
                'verbose_name_plural': 'Фото опций',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
