# Generated by Django 5.2.7 on 2025-10-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price_alter_workphoto_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptionimage',
            name='option',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название работы'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название размера/услуги')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание для этого размера', verbose_name='Описание размера')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товара',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/price_options/', verbose_name='Фото размера')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Описание изображения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('price_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productprice', verbose_name='Размер/Опция')),
            ],
            options={
                'verbose_name': 'Фото размера/опции',
                'verbose_name_plural': 'Фото размеров/опций',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductOptionImage',
        ),
    ]
