# Generated by Django 5.2.7 on 2025-10-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_productoptionimage_option_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('emoji', models.CharField(default='✨', help_text='Например: 🔥, 💧, 🌿', max_length=10, verbose_name='Эмодзи')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Оставьте пустым, если цена не фиксирована', max_digits=10, null=True, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='productprice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание размера'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Фото услуги')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Описание изображения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.additionalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Фото услуги',
                'verbose_name_plural': 'Фото услуг',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductPriceImage',
        ),
    ]
