# Generated by Django 5.2.7 on 2025-10-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_additionalservice_alter_productprice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опции')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание опции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='Фото опции')),
                ('category', models.CharField(choices=[('architecture', '🏛️ Архитектурные элементы'), ('plumbing', '🚿 Сантехника'), ('electrical', '💡 Электрика'), ('furniture', '🪑 Мебель и интерьер'), ('other', '✨ Другое')], default='general', max_length=100, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Глобальная опция',
                'verbose_name_plural': 'Глобальные опции',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='service',
        ),
        migrations.DeleteModel(
            name='AdditionalService',
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
