# Generated by Django 5.2.7 on 2025-10-22 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_globaloption_remove_serviceimage_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaloption',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Глобальная дополнительная услуга', 'verbose_name_plural': 'Глобальные дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AlterModelOptions(
            name='workphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фотография работы', 'verbose_name_plural': 'Фотографии работ'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order_details',
            field=models.TextField(blank=True, verbose_name='Детали заказа'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='category',
            field=models.CharField(choices=[('entrance', '🚪 Прихожая'), ('steam_room', '🔥 Парная'), ('relaxation_room', '🛋️ Комната отдыха'), ('washing_room', '🚿 Мойка'), ('terrace', '🌿 Терраса'), ('porch', '🪜 Крыльцо'), ('windows_doors', '🪟 Окна и двери'), ('lighting', '💡 Освещение'), ('plumbing', '🚰 Сантехника'), ('heating', '🔥 Отопление'), ('furniture', '🪑 Мебель'), ('decoration', '🎨 Отделка'), ('roof', '🏠 Кровля'), ('foundation', '🧱 Фундамент'), ('other', '✨ Другое')], default='other', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='global_options/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
