# Generated by Django 5.2.7 on 2025-10-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_globaloption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workphoto',
            name='title',
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='category',
            field=models.CharField(choices=[('exterior', '🏗️ Внешняя отделка и конструкция'), ('electrical', '⚡ Электрика'), ('doors_windows', '🚪 Двери и окна'), ('lighting', '💡 Освещение'), ('interior', '🎨 Внутренняя отделка'), ('steam_furniture', '🔥 Мебель и оборудование парной'), ('lounge_furniture', '🛋️ Мебель комнаты отдыха'), ('heating', '🌡️ Отопление'), ('washing', '🚿 Помывочная'), ('additional', '✨ Дополнительно')], default='additional', max_length=50, verbose_name='Категория'),
        ),
    ]
