# Generated by Django 5.2.7 on 2025-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_workphoto_title_alter_globaloption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaloption',
            name='category',
            field=models.CharField(choices=[('exterior', '🏗️ Внешняя отделка и конструкция'), ('electrical', '⚡ Электрика'), ('doors_windows', '🚪 Двери и окна'), ('lighting', '💡 Освещение'), ('interior', '🎨 Внутренняя отделка'), ('steam_furniture', '🔥 Мебель и оборудование парной'), ('lounge_furniture', '🛋️ Мебель комнаты отдыха'), ('heating', '🌡️ Отопление'), ('washing', '🚿 Помывочная'), ('additional', '✨ Дополнительно')], db_index=True, default='additional', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='globaloption',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='fio',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AddIndex(
            model_name='globaloption',
            index=models.Index(fields=['is_active', 'category', 'order'], name='shop_global_is_acti_7d29d0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['-created_at'], name='shop_orderr_created_86a3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['phone', 'email'], name='shop_orderr_phone_71bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='shop_produc_title_4a03b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='shop_produc_product_d61400_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'order'], name='shop_produc_product_9d69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workphoto',
            index=models.Index(fields=['-created_at'], name='shop_workph_created_166327_idx'),
        ),
    ]
