# Generated by Django 4.2.7 on 2025-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, help_text='Например: 2.4', max_length=50, verbose_name='Высота (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rest_room',
            field=models.CharField(blank=True, help_text='Например: 170/195 или 2.4', max_length=50, verbose_name='Комната отдыха (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='steam_room_length',
            field=models.CharField(blank=True, help_text='Например: 2.4 или 3', max_length=50, verbose_name='Длина парной (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_length',
            field=models.CharField(blank=True, help_text='Например: 5 или 5.5', max_length=50, verbose_name='Общая длина (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, help_text='Например: 5', max_length=50, verbose_name='Ширина (м)'),
        ),
    ]
